AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Resizer Lambda using S3 trigger and environment variable

Resources:
  ImageResizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: image-resizer-lambda
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: lambda/
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          DEST_BUCKET: image-resizer-destination-bucket-ireland
      Policies:
        - S3ReadPolicy:
            BucketName: image-resizer-source-bucket-ireland
        - S3WritePolicy:
            BucketName: image-resizer-destination-bucket-ireland
      Events:
        ImageUpload:
          Type: S3
          Properties:
            Bucket: image-resizer-source-bucket-ireland
            Events: s3:ObjectCreated:*
